CUDA_VISIBLE_DEVICES=0 python run_summarization.py \
    --mode=decode \
    --data_path=../data/extractive_data/test.txt \
    --vocab_path=../data/extractive_data/vocab.txt \
    --log_root=./log \
    --exp_name=coverage \
    --vocab_size=30000 \
    --coverage=0 \
    --batch_size=128 \
    --single_pass=1